name: Build Odin Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y g++ binutils
          curl -L https://github.com/odin-lang/Odin/releases/download/dev-2025-04/odin-ubuntu-amd64-dev-2025-04.zip -o odin.zip
          unzip odin.zip -d odin
          echo "$GITHUB_WORKSPACE/odin" >> $GITHUB_PATH

      - name: Install Dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gcc binutils
          curl -L https://github.com/odin-lang/Odin/releases/download/dev-2025-04/odin-macos-amd64-dev-2025-04.zip -o odin.zip
          unzip odin.zip -d odin
          echo "$GITHUB_WORKSPACE/odin" >> $GITHUB_PATH

      - name: Install Dependencies (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install mingw -y
          Invoke-WebRequest -Uri https://github.com/odin-lang/Odin/releases/download/dev-2025-04/odin-windows-amd64-dev-2025-04.zip -OutFile odin.zip
          Expand-Archive -Path odin.zip -DestinationPath odin
          echo "$env:GITHUB_WORKSPACE\\odin" | Out-File -Append $env:GITHUB_PATH

      - name: Build with Odin
        run: odin run build.odin -file
