name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Odin
        uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: dev-2025-06

      - name: Install MSVC (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install vcpkg (Windows)
        if: runner.os == 'Windows'
        uses: lukka/run-vcpkg@v11
        with:
          doNotCache: false
          runVcpkgInstall: false
          vcpkgGitCommitId: ce613c41372b23b1f51333815feb3edd87ef8a8b

      - name: Install static OpenSSL (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          vcpkg\vcpkg install openssl:x64-windows-static

      - name: Build debug
        run: |
          odin run build.odin -file -define:DEBUG=true

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: go-${{ matrix.os }}
          path: |
            build/go*
